Repository StoDevX/AAO-React-Native, pull requests merged in 2018-12, with the labels that each got.

#3262 Fix should-skip-build script
  CHANGELOG.md
  scripts/should-skip-build
Labels: tool/build-scripts

#3263 Remove unnecessary flow ignores
  .flowconfig
Labels: tool/flow

#3272 String#unique_lines: Chomp after uniquing
  scripts/should-skip-build
Labels: tool/build-scripts

#3275 ssb: Add #changes_after helper and use it for "yesterday" logic
  CHANGELOG.md
  scripts/should-skip-build
Labels: tool/build-scripts

#3280 Fix circular requires
  CHANGELOG.md
  modules/analytics/report-network-problem.js
  source/views/building-hours/lib/chapel.js
  source/views/building-hours/lib/is-schedule-open.js
  source/views/building-hours/lib/is-schedule-really-open.js
Labels: type/refactoring

#3286 Refactor some stuff around login
  source/redux/index.js
  source/redux/parts/login.js
  source/redux/parts/settings.js
  source/views/settings/screens/overview/login-credentials.js
  source/views/sis/balances.js
  source/views/stoprint/print-jobs.js
Labels: type/refactoring

#3288 disable nightly checks
  scripts/should-skip-build
Labels: tool/circle

#3296 Update interior dependencies
  yarn.lock
Labels: dep/js

#3304 Various Ruby dep updates
  Gemfile.lock
Labels: dep/rb

#3307 Remove now-unused `babel-preset-react-native` package
  package.json
  yarn.lock
Labels: dep/js, type/refactoring

#3308 Fix olecard login
  CHANGELOG.md
  source/lib/login.js
  source/redux/parts/login.js
Labels: type/bugfix, type/refactoring

#3312 Switch from deprecated titlecase dep to frogpond-maintained one
  package.json
  source/views/menus/lib/trim-names.js
  source/views/menus/menu-bonapp.js
  source/views/settings/screens/debug/list.js
  source/views/sis/student-work/index.js
  source/views/streaming/streams/list.js
  yarn.lock
Labels: dep/js

#3314 fastlane: Update support url to match current state
  CHANGELOG.md
  fastlane/metadata/en-US/support_url.txt
Labels: tool/fastlane

#3310 Make it easy to cache requests, and do it
  .eslintrc.yaml
  CHANGELOG.md
  flow-typed/aao/fetch.js
  flow-typed/npm/http-cache-semantics_vx.x.x.js
  modules/ccc-calendar/index.js
  modules/ccc-calendar/package.json
  modules/fetch/cached.js
  modules/fetch/index.js
  modules/fetch/package.json
  source/app.js
  source/init/data.js
  source/init/fetch.js
  source/lib/cache.js
  source/lib/course-search/load-filter-options.js
  source/lib/course-search/update-course-storage.js
  source/lib/financials/balances.js
  source/lib/login.js
  source/lib/stoprint/api.js
  source/redux/parts/help.js
  source/views/building-hours/stateful-list.js
  source/views/contacts/list.js
  source/views/dictionary/list.js
  source/views/faqs/index.js
  source/views/menus/menu-bonapp.js
  source/views/menus/menu-github.js
  source/views/news/news-container.js
  source/views/sis/student-work/index.js
  source/views/streaming/streams/list.js
  source/views/streaming/webcams/list.js
  source/views/student-orgs/list.js
  source/views/transportation/bus/wrapper.js
  source/views/transportation/other-modes/list.js
  yarn.lock
Labels: pr/ready for review, type/refactoring

#3320 Return stale-but-cached data if offline
  CHANGELOG.md
  modules/fetch/cached.js
  source/app.js
Labels: pr/ready for review, type/enhancement, type/refactoring

#3323 Circle: Handle tags more properly
  .circleci/config.yml
  CHANGELOG.md
  scripts/should-skip-build
Labels: tool/circle

#3324 Release v2.7.0, beta 2
  package.json
Labels: type/release

#3341 android: Switch out to the api-28-node image for builds
  .circleci/config.yml
Labels: platform/android, tool/circle

#3344 Fix broken filters
  CHANGELOG.md
  modules/filter/filter-popover.js
  modules/food-menu/fancy-menu.js
Labels: component/filter, type/bugfix

#3345 Add safety view
  CHANGELOG.md
  modules/colors/gradients.js
  modules/open-url/index.js
  modules/open-url/open-url.js
  source/views/home/home.js
  source/views/views.js
Labels: pr/don't merge, type/enhancement

#3350 Fix Filter Popover Bug
  CHANGELOG.md
  modules/filter/filter-toolbar-button.js
Labels: component/filter, type/bugfix

#3352 Only rebuild filters when no filters are applied, not on PTR (Menus)
  CHANGELOG.md
  modules/food-menu/fancy-menu.js
Labels: type/bugfix

#3366 Config file prettification
  .circleci/config.yml
  .renovaterc.json
  e2e/config.json
  package.json
Labels: proposal

#3362 Paper over Privacy Policy crash by removing nested lists
  data/privacy.md
Labels: component/markdown, data/general

#3363 s|US/Central|America/Chicago|g
  CHANGELOG.md
  modules/constants/index.js
  package.json
  scripts/jest-setup.js
  source/init/constants.js
  source/views/building-hours/lib/__tests__/moment.helper.js
  source/views/menus/lib/__tests__/find-menu.test.js
  source/views/transportation/bus/lib/__tests__/moment.helper.js
Labels: type/refactoring

#3371 Bundle Update
  Gemfile.lock
Labels: dep/rb

#3374 Show special BonApp menu messages for closed cafs
  CHANGELOG.md
  modules/food-menu/fancy-menu.js
  modules/food-menu/filter-menu-toolbar.js
  source/views/menus/menu-bonapp.js
Labels: pr/ready for review, type/enhancement, view/menus
