Repository StoDevX/AAO-React-Native, pull requests merged in 2018-08, with the labels that each got.

#2723 Fix cs lag
  source/views/sis/course-search/list.js
  source/views/sis/course-search/search.js
Labels: type/bugfix, view/sis

#2722 Remove menu filters from Redux
  package.json
  source/flux/index.js
  source/flux/parts/courses.js
  source/flux/parts/menus.js
  source/views/components/filter/filter-view.js
  source/views/components/filter/index.js
  source/views/components/searchable-alphabet-listview.js
  source/views/components/searchbar/index.android.js
  source/views/components/searchbar/index.ios.js
  source/views/components/searchbar/types.js
  source/views/dictionary/list.js
  source/views/menus/components/fancy-menu.js
  source/views/menus/dev-bonapp-picker.js
  source/views/menus/menu-bonapp.js
  source/views/menus/menu-github.js
  source/views/sis/components/animated-searchbox.js
  source/views/sis/components/recents-list.js
  source/views/sis/course-search/lib/build-filters.js
  source/views/sis/course-search/lib/execute-search.js
  source/views/sis/course-search/list.js
  source/views/sis/course-search/search.js
  source/views/student-orgs/list.js
  yarn.lock
Labels: type/refactoring, view/menus

#2727 import symbol and array method polyfills
  index.js
Labels: view/sis

#2737 Speed up searching
  source/views/components/alphabet-listview.js
  source/views/components/searchable-alphabet-listview.js
  source/views/sis/course-search/list.js
Labels: type/bugfix, type/refactoring, view/dictionary, view/orgs, view/sis

#2740 use "an approximation of the default behavior for iOS" for header transitions
  source/navigation.js
Labels: platform/ios, type/enhancement

#2741 Add some... interesting Home screen notices
  source/views/home/notice.js
Labels: view/home

#2739 Update KSTO logo
  images/streaming/ksto.png
  source/views/streaming/index.js
  source/views/streaming/radio/controller.js
Labels: status/discussion, view/streaming

#2746 Keyboard dismiss props on course search list
  source/views/sis/course-search/list.js
Labels: pr/ready for review, view/sis

#2749 Lower-case Course search queries
  source/views/sis/course-search/list.js
Labels: view/sis

#2744 Replace FilterView with Interactive FilterToolbar
  package.json
  source/lib/course-search/types.js
  source/lib/course-search/update-course-storage.js
  source/views/components/filter/__tests__/apply-filter.test.js
  source/views/components/filter/__tests__/apply-toggle-filter.test.js
  source/views/components/filter/active-filter-button.js
  source/views/components/filter/filter-popover.js
  source/views/components/filter/filter-toolbar-button.js
  source/views/components/filter/filter-toolbar.js
  source/views/components/filter/index.js
  source/views/components/filter/section.js
  source/views/components/filter/types.js
  source/views/components/toolbar/toolbar.js
  source/views/components/touchable.js
  source/views/menus/components/fancy-menu.js
  source/views/menus/components/filter-menu-toolbar.js
  source/views/menus/lib/build-filters.js
  source/views/sis/components/filter-toolbar.js
  source/views/sis/components/recents-list.js
  source/views/sis/course-search/lib/build-filters.js
  source/views/sis/course-search/lib/format-filter-combo.js
  source/views/sis/course-search/list.js
  source/views/sis/course-search/search.js
  yarn.lock
Labels: pr/ready for review, type/enhancement, view/sis

#2755 Remove old FilterView and references to it
  source/navigation.js
  source/views/components/filter/filter-view.js
  source/views/components/filter/index.js
Labels: component/filter, pr/ready for review

#2756 Add course level filter
  source/views/sis/course-search/lib/build-filters.js
  source/views/sis/course-search/lib/format-filter-combo.js
Labels: component/filter, pr/ready for review, type/enhancement, view/sis

#2760 fix duplicate prettier listing
  package.json
  yarn.lock
Labels: dep/js

#2761 Update Fastlane
  Gemfile.lock
Labels: tool/fastlane

#2762 Release v2.6.0, beta 7
  package.json
Labels: release

#2777 Fix toolbar widths when the toolbar isn't as wide as the screen
  source/views/components/filter/active-filter-button.js
  source/views/components/filter/filter-toolbar-button.js
  source/views/components/filter/filter-toolbar.js
  source/views/components/toolbar/toolbar.js
  source/views/menus/components/filter-menu-toolbar.js
Labels: component/filter, view/menus

#2781 Course Search: Enter browsing mode on empty search bar
  source/views/sis/course-search/search.js
Labels: pr/ready for review, type/enhancement, view/sis

#2787 Wrap <FilterPopover> in <Viewport>
  source/views/components/filter/filter-popover.js
Labels: component/filter, type/bugfix, view/sis

#2790 Push course search results onto the stack
  source/navigation.js
  source/views/components/searchbar/index.android.js
  source/views/components/searchbar/types.js
  source/views/sis/components/animated-searchbox.js
  source/views/sis/course-search/index.js
  source/views/sis/course-search/list.js
  source/views/sis/course-search/results.js
  source/views/sis/course-search/search.js
  source/views/sis/index.js
Labels: type/refactoring

#2566 Add Push Notifications Capability
  android/app/build.gradle
  android/app/src/main/java/com/allaboutolaf/MainApplication.java
  android/settings.gradle
  fastlane/Appfile
  fastlane/Fastfile
  fastlane/README.md
  fastlane/actions/onesignal.rb
  fastlane/platforms/ios.rb
  ios/AllAboutOlaf.xcodeproj/project.pbxproj
  ios/AllAboutOlaf/AllAboutOlaf.entitlements
  ios/AllAboutOlaf/AppDelegate.h
  ios/AllAboutOlaf/AppDelegate.m
  ios/AllAboutOlaf/Info.plist
  ios/AllAboutOlafUITests/AllAboutOlaf-Bridging-Header.h
  ios/OneSignalNotificationServiceExtension/Info.plist
  ios/OneSignalNotificationServiceExtension/NotificationService.h
  ios/OneSignalNotificationServiceExtension/NotificationService.m
  package.json
  source/app.js
  yarn.lock
Labels: pr/don't merge, type/enhancement

#2800 Temporarily migrate to Fastlane's Git as our installation source
  Gemfile
  Gemfile.lock
Labels: pr/ready for review, tool/fastlane

#2798 Use circle's workspaces to move data between jobs
  .circleci/config.yml
Labels: tool/circle

#2801 Update mime-types gems
  Gemfile.lock
Labels: pr/ready for review, tool/fastlane

#2803 Release v2.6.0, beta 8
  package.json
Labels: release

#2799 Course Search: Scroll to top of results list on refresh
  source/views/sis/course-search/list.js
  source/views/sis/course-search/results.js
Labels: pr/ready for review, type/enhancement, view/sis

#2814 Move Student Orgs to ccc-server
  source/views/student-orgs/detail.android.js
  source/views/student-orgs/detail.ios.js
  source/views/student-orgs/list.js
  source/views/student-orgs/util.js
Labels: ccc-server, view/orgs

#2816 Move StudentWork cleaning to ccc-server
  source/views/sis/student-work/clean-job.js
  source/views/sis/student-work/detail.android.js
  source/views/sis/student-work/detail.ios.js
  source/views/sis/student-work/types.js
Labels: view/sis

#2815 Test that we can reach the edit-home view and back
  e2e/views/homescreen/edit.spec.js
  source/views/components/nav-buttons/edit-home.js
Labels: detox, testing, view/edithome

#2818 Update notes about environment variables
  .circleci/config.yml
  .travis.yml
  CONTRIBUTING.md
  README.md
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  source/lib/config.js
Labels: docs

#2819 Add stoPrint View!
  package.json
  source/flux/index.js
  source/flux/parts/stoprint.js
  source/globals.js
  source/lib/stoprint/api.js
  source/lib/stoprint/errors.js
  source/lib/stoprint/index.js
  source/lib/stoprint/types.js
  source/lib/stoprint/urls.js
  source/navigation.js
  source/views/building-hours/report/submit.js
  source/views/components/__tests__/__snapshots__/button.test.js.snap
  source/views/components/button.js
  source/views/components/cells/button.js
  source/views/components/cells/index.js
  source/views/dictionary/report/submit.js
  source/views/stoprint/components/error.js
  source/views/stoprint/components/index.js
  source/views/stoprint/components/notice.js
  source/views/stoprint/index.js
  source/views/stoprint/print-jobs.js
  source/views/stoprint/print-release.js
  source/views/stoprint/printers.js
  source/views/views.js
  yarn.lock
Labels: pr/ready for review, type/enhancement, view/sis

#2828 Update to Android API 28
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
Labels: platform/android, pr/don't merge

#2834 [stoPrint]: Add loading views
  source/views/stoprint/print-jobs.js
  source/views/stoprint/printers.js
Labels: pr/ready for review, type/enhancement, view/stoPrint

#2831 [stoPrint]: Add quotes around documentName and reword alert dialogues
  source/views/stoprint/print-release.js
Labels: pr/ready for review, type/enhancement, view/stoPrint

#2830 Add "Pull to Refresh" to stoPrint notice and error views
  source/views/stoprint/components/error.js
  source/views/stoprint/components/notice.js
  source/views/stoprint/print-jobs.js
Labels: pr/ready for review, type/enhancement, view/stoPrint

#2835 [stoPrint] Fix scrolling in print release view
  source/views/stoprint/print-release.js
Labels: bug/layout, type/bugfix, view/stoPrint

#2837 Run [iOS] Detox in CI
  .circleci/config.yml
  e2e/basic-smoke.spec.js
  e2e/init.js
  e2e/views/homescreen/edit.spec.js
  package.json
Labels: detox, platform/ios, tool/circle

#2839 Add color printers data file
  data/color-printers.yaml
Labels: data/general, pr/ready for review

#2840 [stoPrint] how-to screen tweaks
  source/views/stoprint/components/notice.js
  source/views/stoprint/print-jobs.js
Labels: pr/ready for review, view/stoPrint

#2821 Update JSC on Android
  android/app/build.gradle
  android/build.gradle
  package.json
  yarn.lock
Labels: platform/android

#2843 npm: Make detox an optional dependency
  package.json
Labels: detox, testing

#2851 Update page link in contributing
  CONTRIBUTING.md
Labels: type/documentation

#2854 [stoPrint]: Fix pull-to-refresh bug and fix loading states
  source/flux/parts/stoprint.js
  source/views/stoprint/components/error.js
  source/views/stoprint/components/notice.js
  source/views/stoprint/print-jobs.js
  source/views/stoprint/printers.js
Labels: pr/ready for review, type/bugfix, view/stoPrint

#2858 Prevent open-url tests from importing UI stuff
  source/analytics.js
Labels: type/refactoring

#2850 Fix course search to handle updated data source
  source/lib/course-search/types.js
  source/lib/course-search/update-course-storage.js
  source/views/components/cells/multi-line-detail.js
  source/views/sis/course-search/detail/index.js
  source/views/sis/course-search/lib/build-filters.js
  source/views/sis/course-search/lib/format-dept-num.js
Labels: pr/ready for review, type/bugfix, view/sis

#2861 Split out odds/ends and misc settings into separate files
  source/views/settings/index.js
  source/views/settings/sections/miscellany.js
  source/views/settings/sections/odds-and-ends.js
Labels: view/settings

#2862 Use global repo url in settings
  source/globals.js
  source/views/settings/sections/miscellany.js
Labels: type/refactoring

#2866 Fix formatting of recent filter combo with department filter
  source/views/sis/course-search/lib/format-filter-combo.js
Labels: pr/ready for review, type/bugfix, view/sis

#2863 Fix filter mutation in FilterToolbar
  source/views/components/filter/filter-toolbar.js
Labels: type/refactoring

#2856 Allow unused variables prefixed with _
  .eslintrc.yaml
Labels: tool/eslint

#2876 Fix a prettier issue
  source/views/settings/credits.js
Labels: tool/prettier

#2879 Rename /source/flux to /source/redux
  source/app.js
  source/redux/__tests__/__mocks__/bugsnag-react-native.js
  source/redux/__tests__/update-view-order.test.js
  source/redux/index.js
  source/redux/init.js
  source/redux/parts/app.js
  source/redux/parts/balances.js
  source/redux/parts/buildings.js
  source/redux/parts/courses.js
  source/redux/parts/help.js
  source/redux/parts/homescreen.js
  source/redux/parts/settings.js
  source/redux/parts/stoprint.js
  source/views/building-hours/detail/toolbar-button.js
  source/views/building-hours/stateful-list.js
  source/views/help/index.js
  source/views/home/edit/list.android.js
  source/views/home/edit/list.ios.js
  source/views/home/home.js
  source/views/settings/sections/login-credentials.js
  source/views/settings/sections/odds-and-ends.js
  source/views/sis/balances.js
  source/views/sis/course-search/results.js
  source/views/sis/course-search/search.js
  source/views/stoprint/print-jobs.js
  source/views/stoprint/printers.js
Labels: type/refactoring

#2880 Reorganize app initialization files
  source/app.js
  source/components/open-url.js
  source/init/analytics.js
  source/init/bugsnag.js
  source/init/fetch.js
  source/init/moment.js
  source/lib/analytics.js
  source/lib/api.js
  source/lib/cache.js
  source/lib/constants.js
  source/lib/report-network-problem.js
  source/lib/stoprint/api.js
  source/lib/user-agent.js
  source/navigation.js
  source/navigation/constants.js
  source/navigation/index.js
  source/navigation/navigator.js
  source/navigation/routes.js
  source/navigation/track.js
  source/redux/parts/homescreen.js
  source/redux/parts/settings.js
  source/root.js
  source/views/building-hours/list.js
  source/views/building-hours/report/submit.js
  source/views/building-hours/stateful-list.js
  source/views/calendar/calendar-ccc.js
  source/views/calendar/calendar-util.js
  source/views/calendar/event-list.js
  source/views/contacts/detail.js
  source/views/contacts/list.js
  source/views/dictionary/detail.js
  source/views/dictionary/list.js
  source/views/dictionary/report/submit.js
  source/views/faqs/index.js
  source/views/help/wifi.js
  source/views/menus/menu-bonapp.js
  source/views/menus/menu-github.js
  source/views/news/news-container.js
  source/views/settings/sections/miscellany.js
  source/views/sis/student-work/index.js
  source/views/streaming/radio/controller.js
  source/views/streaming/streams/list.js
  source/views/streaming/webcams/list.js
  source/views/student-orgs/list.js
  source/views/transportation/bus/wrapper.js
  source/views/transportation/other-modes/detail.js
  source/views/transportation/other-modes/list.js
Labels: type/refactoring

#2881 Set up library to allow importing from @app / @frogpond in a monorepo
  .babelrc
  .flowconfig
  package.json
  yarn.lock
Labels: type/refactoring

#2885 [modularize] Move "datepicker" into a module
  modules/datepicker/LICENSE
  modules/datepicker/datepicker.android.js
  modules/datepicker/datepicker.ios.js
  modules/datepicker/index.js
  modules/datepicker/types.js
  source/views/building-hours/report/editor.js
Labels: type/refactoring

#2886 [modularize] Move "touchable" into a module
  modules/touchable/index.js
  source/components/filter/filter-popover.js
  source/components/filter/filter-toolbar-button.js
  source/components/list/list-row.js
  source/components/nav-buttons/close-screen.js
  source/components/nav-buttons/edit-home.js
  source/components/nav-buttons/favorite.js
  source/components/nav-buttons/open-settings.js
  source/components/nav-buttons/share.js
  source/views/building-hours/report/editor.js
  source/views/home/button.js
  source/views/home/edit/row.android.js
  source/views/streaming/radio/buttons.js
  source/views/streaming/webcams/thumbnail.js
Labels: type/refactoring

#2887 [modularize] Move the "list" components into a module
  modules/lists/disclosure-arrow.js
  modules/lists/index.js
  modules/lists/list-empty.js
  modules/lists/list-footer.js
  modules/lists/list-item-detail.js
  modules/lists/list-item-title.js
  modules/lists/list-row.js
  modules/lists/list-section-header.js
  modules/lists/list-separator.js
  modules/separator/index.js
  source/views/building-hours/detail/building.js
  source/views/building-hours/list.js
  source/views/building-hours/report/editor.js
  source/views/building-hours/row.js
  source/views/calendar/event-detail.android.js
  source/views/calendar/event-detail.ios.js
  source/views/calendar/event-list.js
  source/views/calendar/event-row.js
  source/views/contacts/detail.js
  source/views/contacts/list.js
  source/views/contacts/row.js
  source/views/dictionary/detail.js
  source/views/dictionary/list.js
  source/views/menus/carleton-menus.js
  source/views/menus/components/fancy-menu.js
  source/views/menus/components/food-item-row.js
  source/views/news/news-list.js
  source/views/news/news-row.js
  source/views/sis/components/recents-list.js
  source/views/sis/course-search/list.js
  source/views/sis/course-search/results.js
  source/views/sis/course-search/row.js
  source/views/sis/course-search/search.js
  source/views/sis/student-work/index.js
  source/views/sis/student-work/job-row.js
  source/views/stoprint/print-jobs.js
  source/views/stoprint/printers.js
  source/views/streaming/streams/list.js
  source/views/streaming/streams/row.js
  source/views/student-orgs/list.js
  source/views/transportation/bus/components/bus-stop-row.js
  source/views/transportation/bus/line.js
  source/views/transportation/other-modes/detail.js
  source/views/transportation/other-modes/list.js
  source/views/transportation/other-modes/row.js
Labels: type/refactoring

#2878 Share button to job details
  source/views/sis/student-work/detail.android.js
  source/views/sis/student-work/detail.ios.js
  source/views/sis/student-work/lib.js
Labels: view/sis

#2888 [modularize] Move the search bar into a module
  modules/searchbar/index.android.js
  modules/searchbar/index.ios.js
  modules/searchbar/types.js
  source/components/searchable-alphabet-listview.js
  source/views/sis/components/animated-searchbox.js
Labels: type/refactoring

#2889 [modularize] Move AlphabetListView into a @frogpond/listview module
  modules/listview/alphabet-listview.js
  modules/listview/index.js
  modules/listview/searchable-alphabet-listview.js
  source/views/dictionary/list.js
  source/views/student-orgs/list.js
Labels: type/refactoring

#2890 [modularization] Create a "device" module
  modules/device/index.js
  source/views/home/button.js
Labels: type/refactoring

#2893 [modularization] Pull the "Toolbar" component into frogpond/toolbar
  modules/toolbar/index.js
  modules/toolbar/toolbar-button.js
  modules/toolbar/toolbar.js
  source/components/filter/filter-toolbar.js
  source/views/menus/components/filter-menu-toolbar.js
  source/views/menus/dev-bonapp-picker.js
Labels: pr/ready for review, type/refactoring

#2895 [modularization] Re-export react-native-tableview-simple and put our custom cells into a module
  modules/tableview/cells/__tests__/__snapshots__/toggle.test.js.snap
  modules/tableview/cells/__tests__/toggle.test.js
  modules/tableview/cells/button.js
  modules/tableview/cells/delete-button.js
  modules/tableview/cells/index.js
  modules/tableview/cells/multi-line-detail.js
  modules/tableview/cells/multi-line-left-detail.js
  modules/tableview/cells/push-button.js
  modules/tableview/cells/selectable.js
  modules/tableview/cells/textfield.js
  modules/tableview/cells/toggle.js
  modules/tableview/index.js
  source/components/cells/index.js
  source/components/filter/section-list.js
  source/components/filter/section-picker.js
  source/components/filter/section-toggle.js
  source/views/building-hours/detail/schedule-row.ios.js
  source/views/building-hours/detail/schedule-table.android.js
  source/views/building-hours/detail/schedule-table.ios.js
  source/views/building-hours/report/editor.js
  source/views/building-hours/report/overview.js
  source/views/calendar/event-detail.android.js
  source/views/calendar/event-detail.ios.js
  source/views/dictionary/report/editor.js
  source/views/settings/components/login-button.js
  source/views/settings/icon.js
  source/views/settings/index.js
  source/views/settings/sections/login-credentials.js
  source/views/settings/sections/miscellany.js
  source/views/settings/sections/odds-and-ends.js
  source/views/settings/sections/support.js
  source/views/sis/balances.js
  source/views/sis/course-search/detail/index.js
  source/views/sis/student-work/detail.ios.js
  source/views/stoprint/print-release.js
  source/views/student-orgs/detail.ios.js
Labels: pr/ready for review, type/refactoring

#2899 [modularization] Move the lib/api function into frogpond/api
  modules/api/index.js
  source/init/api.js
  source/lib/cache.js
  source/lib/stoprint/api.js
  source/views/building-hours/stateful-list.js
  source/views/calendar/calendar-ccc.js
  source/views/contacts/list.js
  source/views/dictionary/list.js
  source/views/faqs/index.js
  source/views/menus/menu-bonapp.js
  source/views/menus/menu-github.js
  source/views/news/news-container.js
  source/views/sis/student-work/index.js
  source/views/streaming/streams/list.js
  source/views/streaming/webcams/list.js
  source/views/student-orgs/list.js
  source/views/transportation/bus/wrapper.js
  source/views/transportation/other-modes/list.js
Labels: pr/ready for review, type/refactoring

#2898 [modularization] Extract FancyMenu to frogpond/food-menu
  modules/food-menu/dietary-tags.js
  modules/food-menu/fancy-menu.js
  modules/food-menu/filter-menu-toolbar.js
  modules/food-menu/food-item-row.js
  modules/food-menu/index.js
  modules/food-menu/lib/build-filters.js
  modules/food-menu/lib/choose-meal.js
  modules/food-menu/lib/find-menu.js
  modules/food-menu/types.js
  source/views/menus/lib/__tests__/find-menu.test.js
  source/views/menus/menu-bonapp.js
  source/views/menus/menu-github.js
  source/views/menus/types.js
Labels: pr/don't merge, type/refactoring

#2900 [modularization] Pull tabbed-view / TabBarIcon into a frogpond/navigation-tabs module
  modules/navigation-tabs/index.js
  modules/navigation-tabs/tabbar-icon.js
  modules/navigation-tabs/tabbed-view.js
  source/views/calendar/index.js
  source/views/menus/carleton-menus.js
  source/views/menus/dev-bonapp-picker.js
  source/views/menus/index.js
  source/views/news/index.js
  source/views/sis/balances.js
  source/views/sis/course-search/search.js
  source/views/sis/index.js
  source/views/sis/student-work/index.js
  source/views/sis/tes.js
  source/views/streaming/index.js
  source/views/streaming/movie.js
  source/views/streaming/radio/station-krlx.js
  source/views/streaming/radio/station-ksto.js
  source/views/streaming/streams/list.js
  source/views/streaming/webcams/list.js
  source/views/transportation/index.js
  source/views/transportation/other-modes/list.js
Labels: pr/don't merge, type/refactoring

#2901 [modularization] Pull google analytics & bugsnag into frogpond/analytics
  modules/analytics/bugsnag.js
  modules/analytics/google-analytics.js
  modules/analytics/index.js
  modules/analytics/report-network-problem.js
  modules/constants/index.js
  modules/storage/index.js
  source/components/open-url.js
  source/init/analytics.js
  source/init/bugsnag.js
  source/lib/analytics.js
  source/lib/constants.js
  source/lib/report-network-problem.js
  source/lib/storage.js
  source/navigation/track.js
  source/redux/parts/homescreen.js
  source/redux/parts/settings.js
  source/views/building-hours/list.js
  source/views/building-hours/stateful-list.js
  source/views/calendar/calendar-ccc.js
  source/views/calendar/calendar-util.js
  source/views/calendar/event-list.js
  source/views/contacts/detail.js
  source/views/contacts/list.js
  source/views/dictionary/list.js
  source/views/faqs/index.js
  source/views/help/wifi.js
  source/views/menus/menu-bonapp.js
  source/views/menus/menu-github.js
  source/views/news/news-container.js
  source/views/sis/student-work/index.js
  source/views/streaming/radio/controller.js
  source/views/streaming/webcams/list.js
  source/views/student-orgs/list.js
  source/views/transportation/bus/wrapper.js
  source/views/transportation/other-modes/detail.js
  source/views/transportation/other-modes/list.js
Labels: pr/ready for review, type/refactoring

#2902 [modularization] Pull openUrl into frogpond/open-url
  modules/open-url/__tests__/open-url.test.js
  modules/open-url/index.js
  modules/open-url/open-url.js
  source/components/html-view.js
  source/components/markdown/link.js
  source/views/calendar/event-detail.android.js
  source/views/calendar/event-detail.ios.js
  source/views/contacts/detail.js
  source/views/help/tool.js
  source/views/home/home.js
  source/views/news/news-list.js
  source/views/settings/sections/miscellany.js
  source/views/sis/student-work/detail.android.js
  source/views/sis/tes.js
  source/views/stoprint/print-jobs.js
  source/views/streaming/radio/controller.js
  source/views/streaming/streams/row.js
  source/views/streaming/webcams/thumbnail.js
  source/views/student-orgs/detail.android.js
  source/views/student-orgs/detail.ios.js
  source/views/transportation/other-modes/detail.js
Labels: pr/don't merge, type/refactoring

#2903 [modularization] Extract HtmlView to frogpond/html-view
  modules/html-content/index.js
Labels: pr/don't merge, type/refactoring

#2904 [modularization] Move markdown components into frogpond/markdown
  modules/markdown/code.js
  modules/markdown/formatting.js
  modules/markdown/heading.js
  modules/markdown/image.js
  modules/markdown/index.js
  modules/markdown/link.js
  modules/markdown/list.js
  modules/markdown/markdown.js
  modules/markdown/selectable.js
  modules/notice/notice.js
  source/views/contacts/detail.js
  source/views/dictionary/detail.js
  source/views/faqs/index.js
  source/views/help/tool.js
  source/views/help/wifi.js
  source/views/settings/legal.js
  source/views/settings/privacy.js
  source/views/transportation/other-modes/detail.js
Labels: pr/don't merge, type/refactoring

#2905 [modularization] Move button to frogpond/button
  modules/button/__tests__/__snapshots__/button.test.js.snap
  modules/button/__tests__/button.test.js
  modules/button/index.js
  modules/notice/notice.js
  source/views/contacts/detail.js
  source/views/dictionary/detail.js
  source/views/help/tool.js
  source/views/help/wifi.js
  source/views/transportation/other-modes/detail.js
Labels: pr/don't merge, type/refactoring

#2906 [modularization] move IS_PRODUCTION constant to frogpond/constants
  source/init/analytics.js
  source/lib/constants.js
  source/navigation/constants.js
  source/views/building-hours/report/submit.js
  source/views/contacts/detail.js
  source/views/dictionary/detail.js
  source/views/dictionary/report/submit.js
  source/views/settings/sections/miscellany.js
  source/views/transportation/other-modes/detail.js
Labels: type/refactoring

#2910 Fix frogpond api initialization
  source/app.js
Labels: type/bugfix

#2915 Remove the @app namespace
  source/components/add-to-calendar.js
  source/redux/parts/homescreen.js
  source/views/building-hours/report/submit.js
  source/views/contacts/detail.js
  source/views/dictionary/detail.js
  source/views/dictionary/report/submit.js
  source/views/settings/sections/miscellany.js
  source/views/stoprint/components/error.js
  source/views/stoprint/components/notice.js
  source/views/streaming/radio/station-ksto.js
  source/views/transportation/other-modes/detail.js
Labels: type/refactoring

#2916 Remove html-entity stripping from SelectableCell
  .prettierignore
  modules/food-menu/lib/build-filters.js
  modules/html-lib/index.js
  modules/html-lib/package.json
  modules/tableview/cells/selectable.js
  source/views/calendar/event-row.js
  source/views/menus/menu-bonapp.js
  source/views/sis/student-work/detail.ios.js
  source/views/sis/student-work/job-row.js
  source/views/streaming/streams/row.js
  source/views/student-orgs/detail.ios.js
Labels: type/refactoring

#2917 Make use of a central theming library in many places
  modules/app-theme/index.js
  modules/button/__tests__/__snapshots__/button.test.js.snap
  modules/button/__tests__/button.test.js
  modules/button/index.js
  modules/filter/active-filter-button.js
  modules/filter/filter-toolbar-button.js
  modules/layout/column.js
  modules/layout/row.js
  modules/lists/list-section-header.js
  modules/navigation-tabs/tabbed-view.js
  modules/searchbar/animated.js
  modules/searchbar/searchbar.ios.js
  modules/searchbar/types.js
  modules/tableview/cells/__tests__/__snapshots__/toggle.test.js.snap
  modules/tableview/cells/__tests__/toggle.test.js
  modules/tableview/cells/toggle.js
  modules/toolbar/toolbar-button.js
  source/app.js
  source/components/nav-buttons/styles.js
  source/init/theme.js
  source/lib/theme.js
  source/navigation/navigator.js
  source/views/calendar/vertical-bar.js
  source/views/home/home.js
  source/views/sis/components/recents-list.js
Labels: type/refactoring

#2918 Add modules/ to ESLint and Prettier
  package.json
Labels: tool/eslint, tool/prettier

#2922 Update the version of yarn in Travis
  .travis.yml
Labels: tool/travis

#2923 Remove unnecessary viewport
  modules/filter/filter-popover.js
Labels: component/filter

#2848 Staged Hours update for week 35 (08-27—09-02)
  data/building-hours/4-3-rølvaag-library.yaml
  data/building-hours/6-1-skoglund.yaml
  data/building-hours/6-4-tom-porter.yaml
  data/building-hours/6-5-tostrud-climbing-wall.yaml
  data/building-hours/8-alh.yaml
  data/building-hours/8-bc.yaml
  data/building-hours/8-boe.yaml
  data/building-hours/8-cad.yaml
  data/building-hours/8-chm.yaml
  data/building-hours/8-hh.yaml
  data/building-hours/8-hom.yaml
  data/building-hours/8-omh.yaml
  data/building-hours/8-rms.yaml
  data/building-hours/8-rns.yaml
  data/building-hours/8-skifter.yaml
  data/building-hours/8-toh.yaml
Labels: data/hours
