Repository StoDevX/AAO-React-Native, pull requests merged in 2019-02, with the labels that each got.

#3162 Upgrade react-native-vector-icons to version 6.0.2
  CHANGELOG.md
  android/app/src/main/assets/fonts/Ionicons.ttf
  modules/event-list/package.json
  modules/filter/package.json
  modules/food-menu/package.json
  modules/lists/package.json
  modules/navigation-buttons/favorite.js
  modules/navigation-buttons/package.json
  modules/navigation-tabs/package.json
  modules/searchbar/package.json
  package.json
  yarn.lock
Labels: design, pr/ready for review

#3459 TabBarIcon: Add platformPrefixIcon helper and use it
  CHANGELOG.md
  modules/icon/index.js
  modules/icon/package.json
  modules/icon/platform-prefix-icon-name.js
  modules/navigation-tabs/tabbar-icon.js
Labels: design

#3476 Bundle Update
  Gemfile.lock
Labels: dep/rb

#3489 ssb: Also consider optionalDependencies key
  CHANGELOG.md
  scripts/should-skip-build
Labels: dep/js, tool/build-scripts

#3502 Use React.createRef instead of callback refs in a few spots
  modules/tableview/cells/textfield.js
  source/views/settings/screens/overview/login-credentials.js
Labels: type/refactoring

#3501 A few small cleanups in CellTextField and LoginCredentials
  modules/tableview/cells/textfield.js
  source/views/settings/screens/overview/login-credentials.js
Labels: type/refactoring

#3500 Require exact props for CellTextField
  modules/tableview/cells/textfield.js
  source/views/building-hours/report/overview.js
  source/views/dictionary/report/editor.js
Labels: type/refactoring

#3509 Check if disclaimer is agreed to before fetching balances
  CHANGELOG.md
  source/views/sis/balances.js
Labels: pr/ready for review

#3517 Remove Google Analytics
  CHANGELOG.md
  android/app/build.gradle
  android/app/src/main/java/com/allaboutolaf/MainApplication.java
  android/settings.gradle
  data/privacy.md
  flow-typed/npm/react-native-google-analytics-bridge_v5.3.x.js
  ios/AllAboutOlaf.xcodeproj/project.pbxproj
  modules/analytics/google-analytics.js
  modules/analytics/index.js
  modules/analytics/package.json
  modules/analytics/report-network-problem.js
  modules/event-list/event-list.js
  modules/open-url/open-url.js
  package.json
  source/init/analytics.js
  source/lib/analytics.js
  source/lib/storage.js
  source/navigation/track.js
  source/redux/init.js
  source/redux/parts/homescreen.js
  source/redux/parts/login.js
  source/redux/parts/notifications.js
  source/redux/parts/settings.js
  source/views/building-hours/list.js
  source/views/contacts/detail.js
  source/views/dictionary/list.js
  source/views/settings/screens/overview/odds-and-ends.js
  source/views/sis/student-work/index.js
  source/views/streaming/radio/controller.js
  source/views/student-orgs/list.js
  source/views/transportation/other-modes/detail.js
  yarn.lock
Labels: component/analytics

#3515 Rework the Balances acknowledgement behavior
  .flowconfig
  CHANGELOG.md
  flow-typed/npm/react-native-safe-area-view_vx.x.x.js
  modules/button/index.js
  source/views/sis/balances-acknowledgement.js
  source/views/sis/balances.js
  source/views/sis/index.js
Labels: type/enhancement, view/sis
