Repository StoDevX/AAO-React-Native, pull requests merged in 2023-01, with the labels that each got.

#6734 Ready our binary stripping for xcode 14
  ios/AllAboutOlaf.xcodeproj/project.pbxproj
  ios/Podfile
  ios/Podfile.lock
Labels: xcode14

#6768 Add react-native-network-logger dev-only view
  package-lock.json
  package.json
  source/init/network.ts
  source/navigation/routes.tsx
  source/navigation/types.tsx
  source/views/settings/index.ts
  source/views/settings/screens/network-logger/index.tsx
  source/views/settings/screens/overview/developer.tsx
Labels: tool/internal

#6767 Unify api tester debug views
  source/navigation/routes.tsx
  source/views/settings/index.ts
  source/views/settings/screens/api-test/api-test-android.tsx
  source/views/settings/screens/api-test/api-test-ios.tsx
  source/views/settings/screens/api-test/api-test.tsx
  source/views/settings/screens/api-test/index.ts
  source/views/settings/screens/api-test/util/highlight-styles.ts
  source/views/settings/screens/api-test/util/highlight.ts
  source/views/settings/screens/debug/list.tsx
  source/views/settings/screens/overview/developer.tsx
Labels: tool/internal

#4013 🧪 Add end-to-end tests for navigation
  e2e/basic-smoke.spec.ts
  e2e/streaming.spec.ts
  modules/touchable/index.tsx
  source/views/home/button.tsx
  source/views/streaming/streams/list.tsx
  source/views/streaming/webcams/list.tsx
  source/views/streaming/webcams/thumbnail.tsx
Labels: tool/detox, testing
