Repository StoDevX/AAO-React-Native, pull requests merged in 2024-09, with the labels that each got.

#7206 android: Compile with and target Android 14 (API 34)
  android/build.gradle
Labels: platform/android, ci/skip-detox, blocked by unrelated ci failure

#7170 add workflow dispatch to check workflow
  .github/workflows/check.yml
Labels: ci/skip-detox

#7207 remove gradle dep lockfile thru nebula
  android/app/build.gradle
  android/build.gradle
  android/buildscript-gradle.lockfile
Labels: platform/android, ci/skip-detox

#7208 fixup github check annotations
  modules/event-list/times.ts
  modules/filter/filter-popover.tsx
  modules/filter/filter-toolbar-button.tsx
  modules/filter/filter-toolbar.tsx
  modules/markdown/markdown.tsx
  source/lib/course-search/parse-term.ts
  source/redux/parts/courses.ts
  source/views/building-hours/lib/__tests__/parse-hours.test.ts
  source/views/building-hours/lib/chapel.ts
  source/views/contacts/list.tsx
  source/views/dictionary/list.tsx
  source/views/directory/detail.android.tsx
  source/views/directory/list.tsx
  source/views/directory/query.ts
  source/views/directory/types.ts
  source/views/menus/dev-bonapp-picker.tsx
  source/views/more/index.tsx
  source/views/news/news-list.tsx
  source/views/settings/screens/api-test/detail.tsx
  source/views/settings/screens/api-test/list.tsx
  source/views/settings/screens/change-icon.tsx
  source/views/settings/screens/debug/list.tsx
  source/views/settings/screens/overview/app-icon.tsx
  source/views/settings/screens/overview/login-credentials.tsx
  source/views/sis/balances-acknowledgement.tsx
  source/views/sis/course-search/detail/index.tsx
  source/views/sis/course-search/lib/execute-search.ts
  source/views/sis/course-search/lib/format-filter-combo.ts
  source/views/sis/course-search/lib/format-terms.ts
  source/views/sis/course-search/query.ts
  source/views/sis/course-search/search.tsx
  source/views/sis/student-work/query.ts
  source/views/stoprint/print-release.tsx
  source/views/streaming/streams/list.tsx
  source/views/streaming/streams/query.ts
  source/views/student-orgs/detail-android.tsx
  source/views/student-orgs/detail-ios.tsx
  source/views/transportation/bus/lib/__tests__/get-current-bus-iteration.test.ts
  source/views/transportation/bus/lib/__tests__/moment.helper.ts
  source/views/transportation/bus/lib/get-schedule-for-now.ts
  source/views/transportation/bus/line.tsx
Labels: ci/skip-detox

#7129 set a static deployment target in Podfile
  .github/workflows/check.yml
  detox.config.js
  ios/AllAboutOlaf.xcodeproj/project.pbxproj
  ios/Podfile
  ios/Podfile.lock
Labels: ci/skip-detox

#7209 add PrivacyInfo plist for iOS
  ios/AllAboutOlaf.xcodeproj/project.pbxproj
  ios/PrivacyInfo.xcprivacy
Labels: ci/skip-detox

#7214 Update the Renovate config
  renovate.json5
Labels: ci/skip-detox

#7221 update minimum macOS version
  ios/AllAboutOlaf/Info.plist
Labels: ci/skip-detox

#7231 bump ruby version to 3.1
  .github/workflows/build-and-deploy.yml
  .github/workflows/check.yml
  .github/workflows/cocoapods.yml
Labels: ci/skip-detox
